# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_blog', '0002_auto_20170104_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('posts', models.ManyToManyField(to='arch_blog.Post')),
            ],
        ),
    ]
